"""GitHub topics for ML/DL repository search"""
TOPICS = [
    "neural-networks", "convolutional-neural-network", "recurrent-neural-network", "lstm", "gru",
    "attention-mechanism", "bert", "gpt", "stable-diffusion", "yolo", "resnet", "vgg",
    "image-classification", "semantic-segmentation", "instance-segmentation", "face-recognition",
    "speech-recognition", "audio-processing", "time-series", "forecasting", "anomaly-detection",
    "recommendation-system", "embeddings", "transfer-learning", "few-shot-learning", "zero-shot-learning",
    "graph-neural-network", "gnn", "vision-transformer", "clip", "whisper", "chatbot", "text-generation",
    "sentiment-analysis", "named-entity-recognition", "question-answering", "summarization", "translation",
    "ocr", "pose-estimation", "tracking", "machine-learning", "deep-learning", "neural-network",
    "pytorch", "tensorflow", "keras", "scikit-learn", "nlp", "natural-language-processing",
    "computer-vision", "image-processing", "object-detection", "segmentation", "reinforcement-learning",
    "generative-ai", "transformers", "llm", "large-language-model", "diffusion", "gan", "vae", "autoencoder",
    "classification", "regression", "clustering", "data-science", "kaggle", "unsupervised-learning",
    "supervised-learning", "semi-supervised-learning", "meta-learning", "federated-learning",
    "self-supervised-learning", "contrastive-learning", "multi-task-learning", "domain-adaptation",
    "adversarial-training", "explainable-ai", "model-compression", "quantization", "pruning",
    "knowledge-distillation", "automl", "hyperparameter-optimization", "gradient-boosting", "random-forest",
    "svm", "k-means", "dbscan", "pca", "t-sne", "umap", "feature-engineering", "data-augmentation",
    "ensemble-learning", "boosting", "bagging", "cross-validation", "model-selection", "feature-selection",
    "dimensionality-reduction", "representation-learning", "metric-learning", "online-learning",
    "continual-learning", "lifelong-learning", "curriculum-learning", "mixup", "cutmix",
    "adversarial-examples", "adversarial-defense", "robustness", "video-understanding", "video-classification",
    "action-recognition", "video-generation", "optical-flow", "slam", "depth-estimation",
    "object-tracking", "multi-object-tracking", "siamese-networks", "triplet-networks", "maml",
    "model-agnostic-meta-learning", "normalizing-flows", "diffusion-models", "stylegan", "cyclegan",
    "pix2pix", "style-transfer", "super-resolution", "image-captioning", "multimodal-learning",
    "video-segmentation", "ppo", "dqn", "actor-critic", "policy-gradient", "q-learning", "sarsa",
    "monte-carlo", "temporal-difference", "value-iteration", "policy-iteration", "imitation-learning",
    "inverse-reinforcement-learning", "hierarchical-rl", "multi-agent-rl", "multi-armed-bandits",
    "contextual-bandits", "thompson-sampling", "ucb", "epsilon-greedy", "softmax", "boltzmann-exploration",
]
