"""GitHub topics for ML/DL repository search"""
TOPICS = [
    # Core ML/DL
    "neural-networks", "convolutional-neural-network", "recurrent-neural-network", "lstm", "gru",
    "attention-mechanism", "bert", "gpt", "stable-diffusion", "yolo", "resnet", "vgg",
    "image-classification", "semantic-segmentation", "instance-segmentation", "face-recognition",
    "speech-recognition", "audio-processing", "time-series", "forecasting", "anomaly-detection",
    "recommendation-system", "embeddings", "transfer-learning", "few-shot-learning", "zero-shot-learning",
    "graph-neural-network", "gnn", "vision-transformer", "clip", "whisper", "chatbot", "text-generation",
    "sentiment-analysis", "named-entity-recognition", "question-answering", "summarization", "translation",
    "ocr", "pose-estimation", "tracking", "machine-learning", "deep-learning", "neural-network",
    "pytorch", "tensorflow", "keras", "scikit-learn", "nlp", "natural-language-processing",
    "computer-vision", "image-processing", "object-detection", "segmentation", "reinforcement-learning",
    "generative-ai", "transformers", "llm", "large-language-model", "diffusion", "gan", "vae", "autoencoder",
    "classification", "regression", "clustering", "data-science", "kaggle", "unsupervised-learning",
    "supervised-learning", "semi-supervised-learning", "meta-learning", "federated-learning",
    "self-supervised-learning", "contrastive-learning", "multi-task-learning", "domain-adaptation",
    "adversarial-training", "explainable-ai", "model-compression", "quantization", "pruning",
    "knowledge-distillation", "automl", "hyperparameter-optimization", "gradient-boosting", "random-forest",
    "svm", "k-means", "dbscan", "pca", "t-sne", "umap", "feature-engineering", "data-augmentation",
    "ensemble-learning", "boosting", "bagging", "cross-validation", "model-selection", "feature-selection",
    "dimensionality-reduction", "representation-learning", "metric-learning", "online-learning",
    "continual-learning", "lifelong-learning", "curriculum-learning", "mixup", "cutmix",
    "adversarial-examples", "adversarial-defense", "robustness", "video-understanding", "video-classification",
    "action-recognition", "video-generation", "optical-flow", "slam", "depth-estimation",
    "object-tracking", "multi-object-tracking", "siamese-networks", "triplet-networks", "maml",
    "model-agnostic-meta-learning", "normalizing-flows", "diffusion-models", "stylegan", "cyclegan",
    "pix2pix", "style-transfer", "super-resolution", "image-captioning", "multimodal-learning",
    "video-segmentation", "ppo", "dqn", "actor-critic", "policy-gradient", "q-learning", "sarsa",
    "monte-carlo", "temporal-difference", "value-iteration", "policy-iteration", "imitation-learning",
    "inverse-reinforcement-learning", "hierarchical-rl", "multi-agent-rl", "multi-armed-bandits",
    "contextual-bandits", "thompson-sampling", "ucb", "epsilon-greedy", "softmax", "boltzmann-exploration",
    
    # Specific architectures
    "alexnet", "googlenet", "inception", "densenet", "efficientnet", "mobilenet", "shufflenet",
    "squeezenet", "nasnet", "mnasnet", "regnet", "efficientdet", "retinanet", "faster-rcnn",
    "mask-rcnn", "cascade-rcnn", "fpn", "feature-pyramid-network", "u-net", "deeplab", "pspnet",
    "fcn", "segnet", "linknet", "pan", "bisenet", "hrnet", "swin-transformer", "deit", "convnext",
    "mobilevit", "efficientformer", "poolformer", "maxvit", "coatnet", "cvt", "twins",
    
    # NLP models and techniques
    "roberta", "albert", "electra", "xlnet", "t5", "bart", "gpt-2", "gpt-3", "gpt-4", "chatgpt",
    "llama", "alpaca", "vicuna", "bloom", "opt", "flan", "palm", "gemini", "claude", "falcon",
    "word2vec", "glove", "fasttext", "elmo", "ulmfit", "transformer-xl", "xlnet", "xlm",
    "mbert", "distilbert", "tinybert", "spanbert", "sentence-transformers", "sentence-bert",
    "tokenization", "subword", "bpe", "wordpiece", "sentencepiece", "byte-pair-encoding",
    "named-entity-recognition", "ner", "pos-tagging", "dependency-parsing", "constituency-parsing",
    "coreference-resolution", "relation-extraction", "event-extraction", "aspect-based-sentiment",
    "text-classification", "text-clustering", "topic-modeling", "lda", "latent-dirichlet-allocation",
    "text-summarization", "abstractive-summarization", "extractive-summarization", "text-generation",
    "language-modeling", "masked-language-modeling", "causal-language-modeling", "next-token-prediction",
    "machine-translation", "neural-machine-translation", "multilingual", "cross-lingual",
    "code-generation", "code-completion", "program-synthesis", "code-search", "code-review",
    
    # Computer vision techniques
    "image-segmentation", "panoptic-segmentation", "keypoint-detection", "landmark-detection",
    "facial-landmarks", "human-pose-estimation", "hand-pose", "body-pose", "3d-pose",
    "depth-estimation", "monocular-depth", "stereo-depth", "optical-flow", "scene-flow",
    "visual-odometry", "structure-from-motion", "bundle-adjustment", "photogrammetry",
    "image-matching", "feature-matching", "descriptor-learning", "local-features", "sift", "surf",
    "orb", "akaze", "brisk", "superpoint", "superglue", "loftr", "d2-net", "r2d2",
    "image-retrieval", "visual-search", "reverse-image-search", "product-search",
    "image-super-resolution", "srgan", "esrgan", "real-esrgan", "edsr", "rcan",
    "image-inpainting", "image-outpainting", "image-completion", "image-editing",
    "neural-style-transfer", "fast-style-transfer", "arbitrary-style-transfer", "adain",
    "image-colorization", "sketch-to-image", "text-to-image", "image-to-image",
    "image-generation", "image-synthesis", "progressive-gan", "biggan", "stylegan2", "stylegan3",
    "vqgan", "vq-vae", "vq-vae-2", "nva", "vae-gan", "wgan", "lsgan", "began",
    "image-anomaly-detection", "defect-detection", "quality-inspection", "visual-inspection",
    "medical-imaging", "radiology", "x-ray", "ct-scan", "mri", "ultrasound", "pathology",
    "histopathology", "dermatology", "ophthalmology", "retinal", "fundus", "oct",
    "autonomous-driving", "self-driving", "adas", "lane-detection", "traffic-sign-detection",
    "pedestrian-detection", "vehicle-detection", "parking-detection", "obstacle-detection",
    "satellite-imagery", "remote-sensing", "aerial-imagery", "drone", "geospatial",
    "agriculture", "crop-monitoring", "plant-disease", "weed-detection", "precision-agriculture",
    
    # Audio and speech
    "speech-synthesis", "text-to-speech", "tts", "voice-cloning", "voice-conversion",
    "speech-enhancement", "noise-reduction", "denoising", "audio-super-resolution",
    "audio-generation", "music-generation", "audio-classification", "sound-classification",
    "acoustic-scene-classification", "audio-tagging", "music-information-retrieval", "mir",
    "music-transcription", "automatic-music-transcription", "onset-detection", "beat-tracking",
    "pitch-detection", "f0-estimation", "source-separation", "audio-separation", "demixing",
    "speaker-verification", "speaker-identification", "speaker-recognition", "voice-biometrics",
    "speaker-diarization", "voice-activity-detection", "vad", "keyword-spotting", "wake-word",
    "asr", "automatic-speech-recognition", "speech-to-text", "stt", "end-to-end-asr",
    "conformer", "wav2vec", "wav2vec2", "hubert", "wavlm", "speecht5",
    
    # Graph neural networks
    "graph-convolutional-network", "gcn", "graph-attention-network", "gat", "graphsage",
    "graph-isomorphism-network", "gin", "graph-transformer", "graph-transformer-network",
    "message-passing", "graph-matching", "graph-classification", "graph-regression",
    "node-classification", "link-prediction", "graph-embedding", "graph-clustering",
    "community-detection", "graph-partitioning", "knowledge-graph", "kg-embedding",
    "transE", "transR", "distmult", "complEx", "rotate", "convE", "convKB",
    "molecular-property", "drug-discovery", "protein-folding", "protein-structure",
    
    # Time series and forecasting
    "time-series-forecasting", "time-series-prediction", "time-series-classification",
    "time-series-clustering", "time-series-anomaly-detection", "time-series-imputation",
    "arima", "sarima", "exponential-smoothing", "prophet", "lstm-forecasting",
    "temporal-convolutional-network", "tcn", "n-beats", "transformer-forecasting",
    "stock-prediction", "financial-forecasting", "demand-forecasting", "sales-forecasting",
    "energy-forecasting", "load-forecasting", "weather-forecasting", "traffic-forecasting",
    
    # Reinforcement learning
    "deep-q-network", "double-dqn", "dueling-dqn", "prioritized-replay", "rainbow-dqn",
    "a3c", "a2c", "impala", "apex", "r2d2", "agent57", "mu-zero", "alpha-zero",
    "soft-actor-critic", "sac", "td3", "ddpg", "trpo", "natural-policy-gradient",
    "trust-region", "proximal-policy-optimization", "ppo", "gail", "generative-adversarial-imitation",
    "curriculum-rl", "hierarchical-rl", "options-framework", "h-ppo", "h-ddpg",
    "multi-agent", "marl", "independent-actor-critic", "maddpg", "coma", "qmix",
    "value-decomposition", "vdn", "qatten", "qplex", "weighted-qmix",
    "robotics", "robot-learning", "manipulation", "grasping", "navigation", "path-planning",
    "sim-to-real", "domain-randomization", "reality-gap", "robotic-simulation",
    "game-ai", "game-playing", "chess", "go", "poker", "dota", "starcraft", "atari",
    
    # Optimization and training
    "adam", "adamw", "sgd", "momentum", "nesterov", "rmsprop", "adagrad", "adadelta",
    "lamb", "lars", "lookahead", "radam", "novograd", "adafactor", "lion",
    "learning-rate-schedule", "cosine-annealing", "warmup", "cyclic-lr", "one-cycle",
    "gradient-accumulation", "mixed-precision", "fp16", "bf16", "amp", "automatic-mixed-precision",
    "gradient-checkpointing", "activation-checkpointing", "memory-efficient",
    "distributed-training", "data-parallel", "model-parallel", "pipeline-parallel",
    "tensor-parallel", "sharded-data-parallel", "zero", "zero-optimizer", "deepspeed",
    "fairscale", "megatron", "gpipe", "pipedream", "gradient-compression",
    "batch-normalization", "layer-normalization", "instance-normalization", "group-normalization",
    "weight-normalization", "spectral-normalization", "switchable-normalization",
    "dropout", "dropconnect", "spatial-dropout", "dropblock", "stochastic-depth",
    "label-smoothing", "focal-loss", "dice-loss", "iou-loss", "focal-dice",
    
    # Model efficiency
    "model-compression", "network-compression", "model-pruning", "structured-pruning",
    "unstructured-pruning", "magnitude-pruning", "lottery-ticket", "gradual-pruning",
    "quantization", "post-training-quantization", "quantization-aware-training", "qat",
    "int8", "int4", "binary-neural-network", "ternary", "ternarization",
    "knowledge-distillation", "teacher-student", "self-distillation", "online-distillation",
    "feature-distillation", "attention-transfer", "hint-learning",
    "neural-architecture-search", "nas", "darts", "enas", "proxylessnas", "once",
    "once-for-all", "ofa", "big-nas", "spos", "single-path-one-shot",
    "efficient-architecture", "mobile-ai", "edge-ai", "tiny-ml", "microcontroller",
    "onnx", "tensorrt", "openvino", "coreml", "tflite", "ncnn", "mnn",
    
    # Domain-specific
    "bioinformatics", "computational-biology", "genomics", "proteomics", "metabolomics",
    "drug-discovery", "molecular-design", "protein-design", "protein-ligand",
    "cheminformatics", "molecular-property", "qsar", "admet", "toxicity-prediction",
    "finance", "algorithmic-trading", "high-frequency-trading", "risk-modeling",
    "credit-scoring", "fraud-detection", "anti-money-laundering", "aml",
    "recommender-system", "collaborative-filtering", "content-based", "hybrid-recommender",
    "matrix-factorization", "factorization-machines", "field-aware-fm", "ffm",
    "wide-and-deep", "deepfm", "xdeepfm", "autoint", "din", "dien", "miml",
    "e-commerce", "personalization", "search-ranking", "learning-to-rank", "ltr",
    "ctr-prediction", "click-through-rate", "conversion-rate", "cvr",
    "healthcare", "clinical-decision-support", "diagnosis", "prognosis", "treatment",
    "epidemiology", "public-health", "disease-surveillance", "outbreak-prediction",
    "education", "intelligent-tutoring", "adaptive-learning", "educational-data-mining",
    "legal-tech", "legal-ai", "contract-analysis", "legal-search", "case-prediction",
    "supply-chain", "logistics", "inventory-optimization", "demand-planning",
    "manufacturing", "predictive-maintenance", "quality-control", "defect-inspection",
    "energy", "smart-grid", "renewable-energy", "solar-forecasting", "wind-forecasting",
    "climate", "climate-modeling", "weather-prediction", "extreme-weather",
    
    # Frameworks and libraries
    "jax", "flax", "haiku", "optax", "jaxlib", "pytorch-lightning", "lightning",
    "huggingface", "transformers", "datasets", "accelerate", "peft", "trl",
    "mlflow", "wandb", "tensorboard", "neptune", "comet", "clearml",
    "ray", "tune", "rllib", "serve", "workflows", "dask", "modin",
    "onnxruntime", "torchscript", "tvm", "relay", "ansor", "auto-scheduler",
    "triton", "flash-attention", "xformers", "apex", "fairseq", "fairscale",
    "detectron2", "mmdetection", "mmsegmentation", "mmcv", "mmengine",
    "albumentations", "imgaug", "torchvision", "torchaudio", "torchtext",
    "scikit-image", "opencv", "pillow", "imageio", "matplotlib", "seaborn",
    "plotly", "bokeh", "streamlit", "gradio", "dash", "panel",
    "pandas", "numpy", "scipy", "statsmodels", "networkx", "igraph",
    "dgl", "pytorch-geometric", "spektral", "stellargraph", "torch-geometric",
    "nltk", "spacy", "gensim", "textblob", "polyglot", "langdetect",
    "librosa", "audioread", "soundfile", "pydub", "parselmouth", "praat",
    "gym", "gymnasium", "stable-baselines3", "rl-baselines3-zoo", "rllib",
    "tianshou", "dopamine", "tensorforce", "keras-rl", "chainer-rl",
    
    # Research areas
    "causal-inference", "causal-discovery", "causal-ml", "do-calculus",
    "counterfactual", "treatment-effect", "instrumental-variable",
    "fairness", "algorithmic-fairness", "bias-mitigation", "fair-ml",
    "privacy", "differential-privacy", "federated-learning", "secure-aggregation",
    "homomorphic-encryption", "secure-multiparty", "private-ml",
    "interpretability", "explainability", "xai", "shap", "lime", "integrated-gradients",
    "attention-visualization", "saliency-maps", "grad-cam", "grad-cam++",
    "uncertainty-quantification", "bayesian-neural-network", "bnn",
    "monte-carlo-dropout", "ensemble-uncertainty", "conformal-prediction",
    "calibration", "reliability-diagrams", "ece", "expected-calibration-error",
    "out-of-distribution", "ood-detection", "anomaly-detection", "novelty-detection",
    "adversarial-robustness", "certified-defense", "randomized-smoothing",
    "test-time-augmentation", "tta", "test-time-adaptation", "domain-shift",
    "continual-learning", "catastrophic-forgetting", "elastic-weight-consolidation", "ewc",
    "progressive-neural-network", "packnet", "piggyback", "supermasks",
    "neural-tangent-kernel", "ntk", "infinite-width", "wide-neural-network",
    "neural-ode", "ode-net", "continuous-depth", "neural-sde",
    "implicit-neural-representation", "nerf", "sdf", "signed-distance-function",
    "neural-radiance-field", "3d-reconstruction", "multi-view-stereo",
    "neural-rendering", "differentiable-rendering", "volume-rendering",
    "implicit-3d", "mesh-generation", "point-cloud", "voxel", "octree",
]
